#!/bin/bash -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ -z "$DOCKER_HOST" ]; then
  echo "Warning: DOCKER_HOST is not set. Make sure you've set your docker env variables"
  echo "Using default values but this may not work"
fi
export DOCKER_HOST=${DOCKER_HOST:-tcp://192.168.99.100:2376}
export DOCKER_CERT_PATH=${DOCKER_CERT_PATH:-$HOME/.docker/machine/machines/dev}
export DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY:-1}

docker build -t starbound ${DIR}/..
